name: docs_pages_workflow
 
# execute this workflow automatically when a we push to main branch
on:
  push:
    branches: [ main ]
 
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.3'
      - name: Install dependencies for docs
        run: |
          pip install -r requirements-docs.txt
      - name: Install pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.6.4/pandoc-3.6.4-1-amd64.deb
          sudo dpkg -i pandoc-3.6.4-1-amd64.deb
      - name: Install LEAP requirements
        run: |
          pip install -r requirements.txt
      - name: Install LEAP package in editable mode
        run: |
          pip install -e .
      - name: Sphinx build
        run: |
          sphinx-build docs _build -E -a
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true