name: release_workflow

# execute this workflow automatically when a we create a release
on:
  push:

jobs:
  publish_release:
    name: Build and publish Python package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install LEAP requirements
        run: |
          pip install -r requirements.txt
      - name: Install wheel
        run: pip install wheel

      - name: Build a binary wheel and a source tarball
        run: python setup.py bdist_wheel

      - name: Archive package
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/fix-install' }}
        uses: actions/upload-artifact@v4
        with:
          name: leap
          path: dist/

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/leap-1.0-py3-none-any.whl
          asset_name: leap-1.0-py3-none-any.whl
          asset_content_type: application/zip